export const HYDRATE = "__NEXT_REDUX_WRAPPER_HYDRATE__";
export const SHOW_SLIDER = "SHOW_SLIDER";
export const HIDE_SLIDER = "HIDE_SLIDER";
export const ACTIVAE_LOADING = "ACTIVAE_LOADING";
export const DEACTIVAE_LOADING = "DEACTIVAE_LOADING";
export const GET_CHARACTER = "GET_CHARACTER";
